//! Mapping from tiberius errors to Selene's [`CoreError`].
//!
//! Security note: none of these messages can contain credentials. tiberius'
//! `AuthMethod`/`SqlServerAuth` redact the password in their `Debug` impls
//! (`<HIDDEN>`), and we never stringify the `Config` here. Server-provided
//! [`TokenError`] text is generated by SQL Server (e.g. "Invalid object name
//! 'dbo.Foo'") and does not echo the password, so it is safe to surface — it is
//! exactly what a user needs to debug a query.

use tiberius::error::Error as TiberiusError;

use crate::error::CoreError;

/// Convert a general tiberius error into the most appropriate [`CoreError`].
///
/// Used for query execution and ad-hoc statements. Connection-time callers may
/// prefer [`map_connect_err`], which biases ambiguous I/O failures toward
/// [`CoreError::Connection`].
pub(crate) fn map_tiberius_err(err: TiberiusError) -> CoreError {
    match err {
        TiberiusError::Io { kind, message } => CoreError::Io(format!("{kind:?}: {message}")),
        TiberiusError::Protocol(msg) => CoreError::Protocol(msg.into_owned()),
        TiberiusError::Encoding(msg) => CoreError::Protocol(format!("encoding: {msg}")),
        TiberiusError::Conversion(msg) => CoreError::Query(format!("conversion: {msg}")),
        TiberiusError::Utf8 => CoreError::Protocol("invalid UTF-8 from server".into()),
        TiberiusError::Utf16 => CoreError::Protocol("invalid UTF-16 from server".into()),
        TiberiusError::ParseInt(e) => CoreError::Protocol(format!("integer parse: {e}")),
        // A server token error is a query/runtime failure (syntax, permissions,
        // missing object, constraint violation, …). Its message is server-
        // generated and safe to forward.
        TiberiusError::Server(token) => CoreError::Query(format!(
            "{} (code {}, severity {})",
            token.message(),
            token.code(),
            token.class()
        )),
        TiberiusError::Tls(msg) => CoreError::Tls(msg),
        TiberiusError::Routing { host, port } => {
            CoreError::Connection(format!("server requested redirect to {host}:{port}"))
        }
        TiberiusError::BulkInput(msg) => CoreError::Query(format!("bulk input: {msg}")),
        // NOTE: `tiberius::error::Error` has one further variant, `Gssapi`, but
        // it is cfg-gated to `all(unix, feature = "integrated-auth-gssapi")`,
        // which Selene does not enable — so it does not exist in this build and
        // the match above is exhaustive. If that feature is ever turned on, the
        // compiler will flag this match and force an explicit arm.
    }
}

/// Like [`map_tiberius_err`], but used while establishing a connection: bare
/// I/O and TLS failures are reported as connection problems so the UI can drive
/// the right reconnect affordance. A `Server` token at login time (e.g. "Login
/// failed for user") is still a connection/authentication failure.
pub(crate) fn map_connect_err(err: TiberiusError) -> CoreError {
    match err {
        TiberiusError::Io { kind, message } => {
            CoreError::Connection(format!("{kind:?}: {message}"))
        }
        TiberiusError::Server(token) => {
            CoreError::Connection(format!("{} (code {})", token.message(), token.code()))
        }
        // TLS / everything else: defer to the general mapping.
        other => map_tiberius_err(other),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::ErrorKind;

    #[test]
    fn io_error_maps_to_io_for_queries() {
        let e = TiberiusError::Io {
            kind: ErrorKind::ConnectionReset,
            message: "reset".into(),
        };
        assert!(matches!(map_tiberius_err(e), CoreError::Io(_)));
    }

    #[test]
    fn io_error_maps_to_connection_at_connect_time() {
        let e = TiberiusError::Io {
            kind: ErrorKind::ConnectionRefused,
            message: "refused".into(),
        };
        assert!(matches!(map_connect_err(e), CoreError::Connection(_)));
    }

    #[test]
    fn protocol_error_preserved() {
        let e = TiberiusError::Protocol("bad token".into());
        match map_tiberius_err(e) {
            CoreError::Protocol(m) => assert!(m.contains("bad token")),
            other => panic!("expected Protocol, got {other:?}"),
        }
    }

    #[test]
    fn tls_error_maps_to_tls() {
        let e = TiberiusError::Tls("handshake failed".into());
        assert!(matches!(map_tiberius_err(e), CoreError::Tls(_)));
        // And at connect time it stays TLS (not coerced to Connection).
        let e2 = TiberiusError::Tls("handshake failed".into());
        assert!(matches!(map_connect_err(e2), CoreError::Tls(_)));
    }

    #[test]
    fn conversion_error_is_query() {
        let e = TiberiusError::Conversion("nope".into());
        assert!(matches!(map_tiberius_err(e), CoreError::Query(_)));
    }
}
