//! Mapping from `sqlx::Error` to Selene's [`CoreError`] for MySQL.
//!
//! Security note: the password is only ever held inside `MySqlConnectOptions`
//! (and its `Debug` is not redaction-safe, so the options are never logged);
//! none of the error text below embeds it. MySQL's own server messages (e.g.
//! `Unknown column 'foo' in 'field list'`, `You have an error in your SQL
//! syntax …`) are generated by the server and are exactly what a user needs to
//! debug a query, so they are safe to forward.

use sqlx::error::{DatabaseError, Error as SqlxError};
use sqlx::mysql::MySqlDatabaseError;

use crate::error::CoreError;

/// MySQL error number 1045: access denied for user (bad username/password).
const ER_ACCESS_DENIED_ERROR: u16 = 1045;
/// MySQL error number 1049: unknown database (the target database does not exist).
const ER_BAD_DB_ERROR: u16 = 1049;

/// Map a general `sqlx::Error` into the most appropriate [`CoreError`].
///
/// Used for query execution, introspection, and ad-hoc statements. Connect-time
/// callers should prefer [`map_connect_err`], which biases the authentication
/// and bare-I/O failures toward [`CoreError::Connection`].
pub(crate) fn map_sqlx_err(err: SqlxError) -> CoreError {
    match err {
        // A database-reported error: constraint violations, syntax errors,
        // missing columns — all query/runtime failures. The SQLSTATE is prefixed
        // when present for easy correlation.
        SqlxError::Database(db) => CoreError::Query(db_message(db.as_ref())),
        SqlxError::Io(e) => CoreError::Io(format!("{:?}: {e}", e.kind())),
        SqlxError::Tls(e) => CoreError::Tls(e.to_string()),
        SqlxError::Protocol(msg) => CoreError::Protocol(msg),
        // A query expected a row and got none / a column name was missing: query-
        // shaped problems from the caller's point of view.
        SqlxError::RowNotFound | SqlxError::ColumnNotFound(_) => CoreError::Query(err.to_string()),
        // A column failed to decode: a protocol/representation mismatch.
        SqlxError::ColumnDecode { .. } | SqlxError::Decode(_) => {
            CoreError::Protocol(err.to_string())
        }
        // Bad connection options / pool acquisition timeout: configuration issues.
        SqlxError::Configuration(_) | SqlxError::PoolTimedOut => CoreError::Config(err.to_string()),
        // Anything else (PoolClosed, WorkerCrashed, future variants, …) is an
        // unexpected protocol/driver-internal condition.
        other => CoreError::Protocol(other.to_string()),
    }
}

/// Like [`map_sqlx_err`], but used while opening a connection: an access-denied
/// (1045) or unknown-database (1049) error and a bare I/O failure (host
/// down/refused) are connection problems — so the UI drives the right
/// "couldn't connect" affordance.
pub(crate) fn map_connect_err(err: SqlxError) -> CoreError {
    if let SqlxError::Database(db) = &err {
        // MySQL reports the meaningful failure in its native error *number*, not
        // the (coarse) SQLSTATE class, so downcast to read it.
        if let Some(my) = db.try_downcast_ref::<MySqlDatabaseError>() {
            if matches!(my.number(), ER_ACCESS_DENIED_ERROR | ER_BAD_DB_ERROR) {
                return CoreError::Connection(db_message(db.as_ref()));
            }
        }
    }
    if let SqlxError::Io(_) = &err {
        // A bare I/O failure at connect time (refused, unreachable, reset during
        // handshake) is a connection problem.
        return CoreError::Connection(err.to_string());
    }
    map_sqlx_err(err)
}

/// Render a database error to a secret-free message, prefixing the SQLSTATE code
/// when present (e.g. `(SQLSTATE 42S22) Unknown column 'foo' …`).
fn db_message(db: &dyn DatabaseError) -> String {
    match db.code() {
        Some(code) => format!("(SQLSTATE {code}) {}", db.message()),
        None => db.message().to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn row_not_found_is_query() {
        assert!(matches!(
            map_sqlx_err(SqlxError::RowNotFound),
            CoreError::Query(_)
        ));
    }

    #[test]
    fn protocol_error_preserved() {
        match map_sqlx_err(SqlxError::Protocol("bad message".into())) {
            CoreError::Protocol(m) => assert!(m.contains("bad message")),
            other => panic!("expected Protocol, got {other:?}"),
        }
    }

    #[test]
    fn pool_timeout_is_config() {
        assert!(matches!(
            map_sqlx_err(SqlxError::PoolTimedOut),
            CoreError::Config(_)
        ));
    }

    #[test]
    fn column_decode_is_protocol() {
        let e = SqlxError::ColumnDecode {
            index: "0".into(),
            source: "boom".into(),
        };
        assert!(matches!(map_sqlx_err(e), CoreError::Protocol(_)));
    }

    #[test]
    fn bare_io_at_connect_is_connection() {
        let io = std::io::Error::new(std::io::ErrorKind::ConnectionRefused, "refused");
        assert!(matches!(
            map_connect_err(SqlxError::Io(io)),
            CoreError::Connection(_)
        ));
    }
}
