//! Mapping from `mongodb::error::Error` to Selene's [`CoreError`].
//!
//! Security note: MongoDB's error messages are generated by the server/driver
//! and are secret-free — the password lives only in the `Credential` we hand to
//! the driver and is never echoed back in an error. So it is safe to forward the
//! driver's own `Display` text, which is exactly what a user needs to debug a
//! failed connect or command.

use mongodb::error::{Error as MongoError, ErrorKind};

use crate::error::CoreError;

/// Map a general `mongodb::error::Error` into the most appropriate [`CoreError`].
///
/// Used for commands and introspection. Connect-time callers should prefer
/// [`map_connect_err`], which biases auth/selection/io failures toward
/// [`CoreError::Connection`] so the UI drives the right "couldn't connect" path.
pub(crate) fn map_mongo_err(err: MongoError) -> CoreError {
    match err.kind.as_ref() {
        // Bad username/password/mechanism — a connection-level failure.
        ErrorKind::Authentication { .. } => CoreError::Connection(err.to_string()),
        // Could not reach/select a server, or the socket/pool failed.
        ErrorKind::ServerSelection { .. }
        | ErrorKind::Io(_)
        | ErrorKind::ConnectionPoolCleared { .. }
        | ErrorKind::DnsResolve { .. } => CoreError::Connection(err.to_string()),
        // A TLS configuration problem (e.g. a bad CA path).
        ErrorKind::InvalidTlsConfig { .. } => CoreError::Tls(err.to_string()),
        // The server rejected a command (bad query, missing collection, perms).
        ErrorKind::Command(_) | ErrorKind::Write(_) => CoreError::Query(err.to_string()),
        // BSON (de)serialization mismatches are protocol-shaped from our view.
        ErrorKind::BsonDeserialization(_)
        | ErrorKind::BsonSerialization(_)
        | ErrorKind::InvalidResponse { .. } => CoreError::Protocol(err.to_string()),
        // A caller-supplied argument was rejected (e.g. an unparseable URI).
        ErrorKind::InvalidArgument { .. } => CoreError::Config(err.to_string()),
        // Anything else (internal, transaction, incompatible server, future
        // variants, …) — surface as a generic query/protocol failure.
        _ => CoreError::Query(err.to_string()),
    }
}

/// Like [`map_mongo_err`], but used while opening a connection: a command error
/// during the initial liveness check is still fundamentally a "couldn't connect"
/// condition from the user's point of view, so bias those toward
/// [`CoreError::Connection`]. Config/TLS problems keep their specific variants.
pub(crate) fn map_connect_err(err: MongoError) -> CoreError {
    match err.kind.as_ref() {
        ErrorKind::InvalidArgument { .. } => CoreError::Config(err.to_string()),
        ErrorKind::InvalidTlsConfig { .. } => CoreError::Tls(err.to_string()),
        // Everything else at connect time is a connection failure.
        _ => CoreError::Connection(err.to_string()),
    }
}

#[cfg(test)]
mod tests {
    use std::str::FromStr;

    use mongodb::options::AuthMechanism;

    use super::*;

    // `ErrorKind` is `#[non_exhaustive]`, so tests can't construct its variants
    // directly. Instead we build real driver errors through public APIs:
    // `std::io::Error` → `ErrorKind::Io`; a bogus mechanism string →
    // `ErrorKind::InvalidArgument`.

    fn io_error() -> MongoError {
        std::io::Error::new(std::io::ErrorKind::ConnectionRefused, "refused").into()
    }

    fn invalid_argument_error() -> MongoError {
        AuthMechanism::from_str("NOT-A-REAL-MECHANISM").expect_err("bogus mechanism must error")
    }

    #[test]
    fn io_maps_to_connection() {
        assert!(matches!(
            map_mongo_err(io_error()),
            CoreError::Connection(_)
        ));
    }

    #[test]
    fn invalid_argument_maps_to_config() {
        assert!(matches!(
            map_mongo_err(invalid_argument_error()),
            CoreError::Config(_)
        ));
    }

    #[test]
    fn connect_err_biases_io_to_connection() {
        assert!(matches!(
            map_connect_err(io_error()),
            CoreError::Connection(_)
        ));
    }

    #[test]
    fn connect_err_keeps_config_specific() {
        // An invalid-argument (e.g. unparseable URI) stays a config error even on
        // the connect-biased path.
        assert!(matches!(
            map_connect_err(invalid_argument_error()),
            CoreError::Config(_)
        ));
    }
}
