//! Mapping from `sqlx::Error` to Selene's [`CoreError`].
//!
//! Security note: SQLite has no credentials, so none of these messages can leak
//! a secret. SQLite's own error text (e.g. "no such table: foo", "near \"slect\":
//! syntax error") is generated by the engine and is exactly what a user needs to
//! debug a query, so it is safe to forward.

use sqlx::error::{DatabaseError, Error as SqlxError};

use crate::error::CoreError;

/// SQLite primary result code for "unable to open the database file"
/// (`SQLITE_CANTOPEN`).
const SQLITE_CANTOPEN: &str = "14";
/// SQLite primary result code for "file is not a database" (`SQLITE_NOTADB`).
const SQLITE_NOTADB: &str = "26";

/// Map a general `sqlx::Error` into the most appropriate [`CoreError`].
///
/// Used for query execution, introspection, and ad-hoc statements. Connect-time
/// callers should prefer [`map_connect_err`], which biases the file-access codes
/// toward [`CoreError::Connection`].
pub(crate) fn map_sqlx_err(err: SqlxError) -> CoreError {
    match err {
        // A database-reported error: constraint violations, syntax errors,
        // missing objects — all query/runtime failures.
        SqlxError::Database(db) => CoreError::Query(db_message(db.as_ref())),
        SqlxError::Io(e) => CoreError::Io(format!("{:?}: {e}", e.kind())),
        SqlxError::Tls(e) => CoreError::Tls(e.to_string()),
        SqlxError::Protocol(msg) => CoreError::Protocol(msg),
        // A query expected a row and got none / a column failed to decode / a
        // column name was missing: all query-shaped problems from the caller's
        // point of view.
        SqlxError::RowNotFound | SqlxError::ColumnNotFound(_) => CoreError::Query(err.to_string()),
        SqlxError::ColumnDecode { .. } | SqlxError::Decode(_) => {
            CoreError::Protocol(err.to_string())
        }
        // Bad connection string / pool acquisition timeout: configuration issues.
        SqlxError::Configuration(_) | SqlxError::PoolTimedOut => CoreError::Config(err.to_string()),
        // Anything else (PoolClosed, WorkerCrashed, future variants, …) is an
        // unexpected protocol/driver-internal condition.
        other => CoreError::Protocol(other.to_string()),
    }
}

/// Like [`map_sqlx_err`], but used while opening a connection: a database-level
/// "can't open"/"not a database" code is a connection/config problem rather than
/// a query failure, so the UI drives the right "couldn't connect" affordance.
pub(crate) fn map_connect_err(err: SqlxError) -> CoreError {
    if let SqlxError::Database(db) = &err {
        match db.code().as_deref() {
            // The file does not exist / is not accessible (we open with
            // create_if_missing(false), so a missing file lands here).
            Some(SQLITE_CANTOPEN) => return CoreError::Connection(db_message(db.as_ref())),
            // The file exists but is not a valid SQLite database.
            Some(SQLITE_NOTADB) => return CoreError::Config(db_message(db.as_ref())),
            _ => {}
        }
    }
    if let SqlxError::Io(_) = &err {
        // A bare I/O failure at connect time is a connection problem.
        return CoreError::Connection(err.to_string());
    }
    map_sqlx_err(err)
}

/// Render a database error to a secret-free message, prefixing the SQLite result
/// code when present (e.g. "(code 1) no such table: foo").
fn db_message(db: &dyn DatabaseError) -> String {
    match db.code() {
        Some(code) => format!("(code {code}) {}", db.message()),
        None => db.message().to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn row_not_found_is_query() {
        assert!(matches!(
            map_sqlx_err(SqlxError::RowNotFound),
            CoreError::Query(_)
        ));
    }

    #[test]
    fn protocol_error_preserved() {
        match map_sqlx_err(SqlxError::Protocol("bad token".into())) {
            CoreError::Protocol(m) => assert!(m.contains("bad token")),
            other => panic!("expected Protocol, got {other:?}"),
        }
    }

    #[test]
    fn pool_timeout_is_config() {
        assert!(matches!(
            map_sqlx_err(SqlxError::PoolTimedOut),
            CoreError::Config(_)
        ));
    }

    #[test]
    fn column_decode_is_protocol() {
        let e = SqlxError::ColumnDecode {
            index: "0".into(),
            source: "boom".into(),
        };
        assert!(matches!(map_sqlx_err(e), CoreError::Protocol(_)));
    }
}
