//! Mapping from `sqlx::Error` to Selene's [`CoreError`] for Postgres.
//!
//! Security note: the password is only ever held inside `PgConnectOptions` (and
//! is not echoed by its `Debug`); none of the error text below embeds it.
//! Postgres' own server messages (e.g. `relation "foo" does not exist`,
//! `syntax error at or near "slect"`) are generated by the server and are
//! exactly what a user needs to debug a query, so they are safe to forward.

use sqlx::error::{DatabaseError, Error as SqlxError};

use crate::error::CoreError;

/// SQLSTATE class `28` — invalid authorization specification (`28000`) and
/// invalid password (`28P01`).
const SQLSTATE_CLASS_AUTH: &str = "28";
/// SQLSTATE `3D000` — invalid catalog name (the database does not exist).
const SQLSTATE_INVALID_CATALOG: &str = "3D000";

/// Map a general `sqlx::Error` into the most appropriate [`CoreError`].
///
/// Used for query execution, introspection, and ad-hoc statements. Connect-time
/// callers should prefer [`map_connect_err`], which biases the authentication
/// and bare-I/O failures toward [`CoreError::Connection`].
pub(crate) fn map_sqlx_err(err: SqlxError) -> CoreError {
    match err {
        // A database-reported error: constraint violations, syntax errors,
        // missing relations — all query/runtime failures. The SQLSTATE is
        // prefixed when present for easy correlation.
        SqlxError::Database(db) => CoreError::Query(db_message(db.as_ref())),
        SqlxError::Io(e) => CoreError::Io(format!("{:?}: {e}", e.kind())),
        SqlxError::Tls(e) => CoreError::Tls(e.to_string()),
        SqlxError::Protocol(msg) => CoreError::Protocol(msg),
        // A query expected a row and got none / a column name was missing: query-
        // shaped problems from the caller's point of view.
        SqlxError::RowNotFound | SqlxError::ColumnNotFound(_) => CoreError::Query(err.to_string()),
        // A column failed to decode: a protocol/representation mismatch.
        SqlxError::ColumnDecode { .. } | SqlxError::Decode(_) => {
            CoreError::Protocol(err.to_string())
        }
        // Bad connection options / pool acquisition timeout: configuration issues.
        SqlxError::Configuration(_) | SqlxError::PoolTimedOut => CoreError::Config(err.to_string()),
        // Anything else (PoolClosed, WorkerCrashed, future variants, …) is an
        // unexpected protocol/driver-internal condition.
        other => CoreError::Protocol(other.to_string()),
    }
}

/// Like [`map_sqlx_err`], but used while opening a connection: authentication
/// failures (SQLSTATE class `28`) and a missing target database (`3D000`) are
/// connection problems, and a bare I/O failure (host down/refused) is too — so
/// the UI drives the right "couldn't connect" affordance.
pub(crate) fn map_connect_err(err: SqlxError) -> CoreError {
    if let SqlxError::Database(db) = &err {
        if let Some(code) = db.code() {
            // `28xxx` (auth) and `3D000` (invalid catalog/db) are connection-time
            // failures, not query failures.
            if code.starts_with(SQLSTATE_CLASS_AUTH) || code == SQLSTATE_INVALID_CATALOG {
                return CoreError::Connection(db_message(db.as_ref()));
            }
        }
    }
    if let SqlxError::Io(_) = &err {
        // A bare I/O failure at connect time (refused, unreachable, reset during
        // handshake) is a connection problem.
        return CoreError::Connection(err.to_string());
    }
    map_sqlx_err(err)
}

/// Render a database error to a secret-free message, prefixing the SQLSTATE code
/// when present (e.g. `(SQLSTATE 42P01) relation "foo" does not exist`).
fn db_message(db: &dyn DatabaseError) -> String {
    match db.code() {
        Some(code) => format!("(SQLSTATE {code}) {}", db.message()),
        None => db.message().to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn row_not_found_is_query() {
        assert!(matches!(
            map_sqlx_err(SqlxError::RowNotFound),
            CoreError::Query(_)
        ));
    }

    #[test]
    fn protocol_error_preserved() {
        match map_sqlx_err(SqlxError::Protocol("bad message".into())) {
            CoreError::Protocol(m) => assert!(m.contains("bad message")),
            other => panic!("expected Protocol, got {other:?}"),
        }
    }

    #[test]
    fn pool_timeout_is_config() {
        assert!(matches!(
            map_sqlx_err(SqlxError::PoolTimedOut),
            CoreError::Config(_)
        ));
    }

    #[test]
    fn column_decode_is_protocol() {
        let e = SqlxError::ColumnDecode {
            index: "0".into(),
            source: "boom".into(),
        };
        assert!(matches!(map_sqlx_err(e), CoreError::Protocol(_)));
    }
}
